# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # -------------------------------------------------
      # 1. Checkout code
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -------------------------------------------------
      # 2. Set up Python
      # -------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # -------------------------------------------------
      # 3. Install Python dependencies
      # -------------------------------------------------
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------------------------------
      # 4. Install Playwright browsers (required!)
      # -------------------------------------------------
      - name: Install Playwright browsers
        run: |
          playwright install

      # -------------------------------------------------
      # 5. Run unit tests (no server needed)
      # -------------------------------------------------
      - name: Run unit tests (pytest)
        run: |
          pytest tests/ -vv

      # -------------------------------------------------
      # 6. Start Flask app in background
      # -------------------------------------------------
      - name: Start Flask application
        run: |
          nohup python app.py > app.log 2>&1 &
          echo "Flask started – PID $!"

      # -------------------------------------------------
      # 7. Wait for the server to be ready
      # -------------------------------------------------
      - name: Wait for Flask to be reachable
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 10
          command: |
            curl -f http://127.0.0.1:5000/ || exit 1

      # -------------------------------------------------
      # 8. Run Playwright E2E tests
      # -------------------------------------------------
      - name: Run Playwright E2E tests
        run: |
          pytest e2e/ -vv

      # -------------------------------------------------
      # 9. Build Docker image
      # -------------------------------------------------
      - name: Build Docker image
        run: |
          docker build -t myflaskapp .

      # -------------------------------------------------
      # 10. (Optional) Show Flask log on failure
      # -------------------------------------------------
      - name: Show Flask log (on failure)
        if: failure()
        run: cat app.log